server:
  port: 7001
eureka:
  instance:
    # eureka服务端的实例名称
    prefer-ip-address: true
    hostname: eureka7001.com

  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/ #集群模式指向其他eureka

      defaultZone: http://eureka7001.com:7001/eureka/ #单机就自己
#
#  server:
#    enable-self-preservation: false  #禁止自我保护机制，默认开启
#    a-s-g-update-interval-ms: 2000   #时间